### ISSUE TITLE
approach for responsively switching up layout components

### ISSUE THREAD

**Issue by sdebaun** [sdebaun/sparks-cyclejs#10]
#7 contains a half-implemented Dash page (manually navigate to /dash for now)

https://github.com/sdebaun/sparks-cyclejs/blob/release/js/components/Dash.js

the styling got a bit borked from the merge, we each started using .row and .col classes in different ways. :)  nevermind all that, see what i started trying to do with different mobile and desktop layout components.  basically some routes have layouts that vary significantly in composition, more than i know how to do in css.  See some of the feature cards eg --

https://trello.com/c/yZ63rYLe/37-volunteers-can-apply-for-opportunities
See last two images, how tab location, background, lots of things are varying

@TylorS  there are a couple bugs that i think i'm finally understanding, but does this look like a valid approach to you?  any other suggestions?

**Comment by TylorS** [comment]
This approach seems sound to me. The only other method in which I could see working here is very imperative and would probably grow unwieldy very quickly.

**Comment by TylorS** [comment]
You mention bugs, are they application bugs or external bugs?
If there are any bugs which need fixing please don't hesitate to ask.

**Comment by TylorS** [comment]
I believe this is solved now?
