### ISSUE TITLE
firebase driver

### ISSUE THREAD

**Issue by sdebaun** [sdebaun/sparks-cyclejs#11]
https://github.com/sdebaun/sparks-cyclejs/blob/firebase/js/drivers/firebaseDriver.js
was one of the first things i wrote in the cyclejs experimental project
(i just threw it in the repo, its not hooked up to anything)

there are also a bunch of firebase drivers out there, i looked them over when i started, and i still decided to write my own.  'i didnt like the others, they were too flat'.

two domain-specific features in the one i wrote, should probably extend a generic driver rather than be baked in --

the method signature firebase.watch(collectionName,args) where args can be either an object, in which case a query is built from the keys, otherwise its treated as a key.  just a shortcut to .child(collectionName).child(args).  Thats super convenient because of the way im structuring the back end data.

similarly all mutation of the backend happens through a firebase queue, so we're able to treat the firebase sink as a single input stream of queue'd actions.  those actions are processed on the backend by workers.  this is all implemented in sparks-react, when i port it over i will probably turn it into observables.

so yeah now that i get frp better, it probably makes more sense to have a more generic driver and have a function that transforms the sinks/sources somewhere in the App component?

@TylorS

**Comment by TylorS** [comment]
I want to frame all of my responses with the fact I have not previously worked with Firebase in any other capacity than maybe the first half of their tutorial.

> two domain-specific features in the one i wrote, should probably extend a generic driver rather than be baked in

If some of the other Firebase drivers work similarly to how you'd like but do not offer these 2 features it is possible to create a higher-order driver to wrap another one with your feature built in.
Some psuedocode for it

``` js
import {makeSomeOtherFBDriver} from 'somewhere'

function makeFBDriver(options) {
  const otherFBDriver = makeSomeOtherFBDriver(options)
  return function FBDriver(sink$) {
    // do domain-specific things with sink$

    const otherSources = otherFBDriver(sink$)
    // mokeypatch the other driver or extend it with features

    return {
      ...otherSources,
      // add domain-specific sources
    }
  }
}
```

>  it probably makes more sense to have a more generic driver and have a function that transforms the sinks/sources somewhere in the App component?

This sounds like a good idea to me. Functions are cheap, testable, and very powerful.

**Comment by sdebaun** [comment]
ok, i looked more at cycle-firebase, and i think were ok if i just clean up what we've got.  the cycle-firebase project didnt really blow my skirt up:

https://github.com/dralletje/cycle-firebase/blob/master/src/firebase.js#L80

Firebase is super simple, I'm going to clean up the driver i wrote and start using it

**Comment by TylorS** [comment]
Okay, I can get behind that 100% :+1:

**Comment by TylorS** [comment]
I think it's safe to close this issues then?

**Comment by sdebaun** [comment]
yup! #17

**Comment by scottcorgan** [comment]
Any thoughts on pulling out and open sourcing your firebase driver?

**Comment by sdebaun** [comment]
hi @scottcorgan i would love to!  that was actually something i wanted to do -- see #9, i just havent done that yet.  i have never actually published a module to NPM before, i guess its time to now!

**Comment by scottcorgan** [comment]
Please do. I've got my own driver, but yours has what looks like more use. I'd love to just have one go to that works well. cycle-firebase ain't my thing either.

**Comment by sdebaun** [comment]
looking at it right now.  what cycle-related name can we use that isnt taken? @TylorS

**Comment by TylorS** [comment]
cyclic-fire isn't taken

**Comment by TylorS** [comment]
cyclic-firebase / cyclic-**

**Comment by sdebaun** [comment]
hm, thats a great name, but github just recommended `reimagined-octo-shuffle`, and i decided to go with that instead.

just kidding.  BEHOLD:

https://github.com/sdebaun/cyclic-fire

an empty repository.  porting code now, will publish shortly

**Comment by TylorS** [comment]
:+1:

**Comment by sdebaun** [comment]
@scottcorgan ive got the first attempt published as cyclic-fire, can you try it out and tell me if it works for you?
