### ISSUE TITLE
Add more descriptive issue labels

### ISSUE THREAD

**Issue by TylorS** [sdebaun/sparks-cyclejs#14]
# Overview

Github issues can be a really great way to keep track of a project and problems especially when there are more descriptive issue labels and external applications can be used to facilitate them very nicely.
I have experience with https://waffle.io but I believe Trello can be used for this as well, I'd have to look into that further.
# References

Take note of the descriptive issue labels :smile: 

I have used this approach for Motorcyclejs from the get-go and it's been very useful to me as a lone project manager.

Example issue: https://github.com/motorcyclejs/core/issues/46
Waffle.io board: https://waffle.io/motorcyclejs/motorcycle

Just a few days ago, and probably better done, we have also moved the Cycle.js project using this system. 

Example issue: https://github.com/cyclejs/core/issues/238
Waffle.io board: https://waffle.io/cyclejs/core

@sdebaun Would love to get your thoughts and feedback on this.

**Comment by sdebaun** [comment]
with trello, you could achieve some of this, but with a lot more work, and not as integrated

waffle looks awesome, im wondering how we fit it in -- i think its solving a different set of problems than what we're trying to do with our trello feature board.  the trello board is a channel for user feedback, it needs to be visual, friendly, accessible to non-techs.  our users would be scared off by waffle, i think.

we need to figure out how to tie the engineering-oriented view, involving PR and probably waffle, to the stakeholder-facing view (trello), both technically, and wrt workflow.

those new labels look good -- are they just added to the repo by hand?

**Comment by TylorS** [comment]
Yes they are. We have a script to add all of the labels that are used with motorcycle [here](https://github.com/motorcyclejs/motorcycle/blob/master/scripts/gh-labels.sh)

I believe the ones added for Cycle.js were added entirely by hand.

**Comment by sdebaun** [comment]
closing this in favor of a bigger discussion in #42
