### ISSUE TITLE
choose either material Row() or div('.row')

### ISSUE THREAD

**Issue by sdebaun** [sdebaun/sparks-cyclejs#15]
the snabbdom-material library comes with Row() and Col() vdom helpers
looks like newly added .row class conflicts with that
@TylorS any reason not to standardize on Row() and Col()?

**Comment by TylorS** [comment]
I don't think there is any reason not to standardize on the Row() and Col() provided by snabbdom-material.

**Comment by sdebaun** [comment]
#18 makes them consistent... not actually terribly impressed with Row(), looks like you cant override styles??
