### ISSUE TITLE
URL is being thrashed on /project/:key page

### ISSUE THREAD

**Issue by TylorS** [sdebaun/sparks-cyclejs#35]
When clicking on a tab the route is always being appended to the current route, which ends up with a crazy URL like you can see here in this picture.

![screenshot from 2016-03-08 09-37-22](https://cloud.githubusercontent.com/assets/6282473/13604602/862fba7a-e511-11e5-9ff3-69b395adc6da.png)

**Comment by sdebaun** [comment]
i saw this, i have no idea why its doing it
