### ISSUE TITLE
include eslint in the development watch

### ISSUE THREAD

**Issue by sdebaun** [sdebaun/sparks-cyclejs#8]
would love to see lint errors as i create them, is there a simpler way that doesnt involve gulp, or is it time to use gulp? @TylorS

**Comment by TylorS** [comment]
This should be very easy to do with just npm scripts. I'll take care of this first today.

What editor do you use? I'd really highly recommend finding a plugin to see eslint errors in real-time from right inside of your editor. I personally use Atom with linter-eslint to great success.

**Comment by TylorS** [comment]
I'm also going to investigate options to do this simply with webpack.

**Comment by sdebaun** [comment]
Awesome, per your suggestion i found a plugin for sublime that lints while-you-work.  you're right, thats way better :)

**Comment by TylorS** [comment]
Awesome :+1:
